[package]
name = "url_query"
version = "0.1.0"
authors = ["Alexandr Krikun <krikun.contact@ya.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
